const $ = s => document.querySelector(s)
const toast = text => { const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600) }
const remaining = u => u && u.remaining != null ? (u.limit != null ? `${u.remaining} / ${u.limit}` : `${u.remaining}`) : 'ยังไม่มีข้อมูล'
const reset = u => { if(!u?.resetAt) return 'เปิดแอปเพื่อบันทึกสถานะ'; const ms=Date.parse(u.resetAt)-Date.now(); if(ms<=0)return 'ถึงเวลารีเซ็ตแล้ว · เปิดแอปเพื่อยืนยัน'; const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4); return `เต็มอีกครั้งใน ${h} ชม. ${m} นาที` }
async function load(){ const d=await manager.overview(); $('#count').textContent=d.clones.length; $('#version').textContent=`เวอร์ชัน ${d.version}`; $('#cards').innerHTML=d.clones.map(c=>`<article class="card"><div class="card-head"><div class="avatar">${c.IconLetter||c.Name.slice(-1)}</div><span class="muted">${c.installed?'พร้อมใช้':'ยังไม่สร้าง'}</span></div><h4>${c.Name}</h4><div class="muted">${reset(c.usage)}</div><div class="meter"><span style="width:${c.usage&&c.usage.limit?Math.max(0,Math.min(100,c.usage.remaining/c.usage.limit*100)):0}%"></span></div><div class="quota"><span>คงเหลือ</span><b>${remaining(c.usage)}</b></div><button class="secondary" data-open="${c.Name}">เปิดบัญชี</button></article>`).join('')||'<p class="muted">ยังไม่มีแอปโคลน</p>'; $('#account-list').innerHTML=d.clones.map(c=>`<div class="account-row"><span>${c.Name}</span><span class="muted">${remaining(c.usage)} · ${reset(c.usage)}</span></div>`).join(''); document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run('open-clone',{name:b.dataset.open})) }
async function run(a,p){try{toast('กำลังดำเนินการ…');const r=await manager.run(a,p);if(r.message){$('#log-text').textContent=r.message;$('#log').showModal()}toast('ดำเนินการสำเร็จ');await load()}catch(e){toast(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');$('#title').textContent=b.querySelector('span').textContent})
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>run(b.dataset.action))
let updateState=null
async function checkUpdates(){try{toast('กำลังตรวจ GitHub Releases…');updateState=await manager.checkUpdates();$('#language-version').textContent=`ปัจจุบัน ${updateState.language.current} · ล่าสุด ${updateState.language.latest}`;$('#manager-version').textContent=`ปัจจุบัน ${updateState.manager.current} · ล่าสุด ${updateState.manager.latest}`;const lb=$('#update-language'),mb=$('#update-manager');lb.disabled=!updateState.language.available;mb.disabled=!updateState.manager.available;lb.textContent=updateState.language.available?'อัปเดตภาษาไทย':'เป็นเวอร์ชันล่าสุด';mb.textContent=updateState.manager.available?'อัปเดต Manager':'เป็นเวอร์ชันล่าสุด';$('#update-all').disabled=!(updateState.language.available||updateState.manager.available);$('#release').textContent=updateState.notes||'ตรวจสอบ Release ล่าสุดเรียบร้อยแล้ว';toast('ตรวจสอบอัปเดตแล้ว')}catch(e){toast(e.message)}}
async function installUpdate(kind){try{toast('กำลังดาวน์โหลดและตรวจ SHA-256…');const r=await manager.installUpdate(kind);$('#log-text').textContent=r.message;$('#log').showModal();if(!r.restart)await checkUpdates()}catch(e){toast(e.message)}}
$('#refresh').onclick=load;$('#close-log').onclick=()=>$('#log').close();$('#check-update').onclick=checkUpdates;$('#update-language').onclick=()=>installUpdate('language');$('#update-manager').onclick=()=>installUpdate('manager');$('#update-all').onclick=async()=>{if(updateState?.language.available)await installUpdate('language');if(updateState?.manager.available)await installUpdate('manager')}
load();setInterval(load,60000)
