const $ = s => document.querySelector(s)
const toast = text => { const el=$('#toast'); el.textContent=text; el.classList.add('show'); setTimeout(()=>el.classList.remove('show'),2600) }
const remaining = u => u && u.remaining != null ? (u.limit != null ? `${u.remaining} / ${u.limit}` : `${u.remaining}`) : 'ยังไม่มีข้อมูล'
const reset = u => { if(!u?.resetAt) return 'เปิดแอปเพื่อบันทึกสถานะ'; const ms=Date.parse(u.resetAt)-Date.now(); if(ms<=0)return 'ถึงเวลารีเซ็ตแล้ว · เปิดแอปเพื่อยืนยัน'; const h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4); return `เต็มอีกครั้งใน ${h} ชม. ${m} นาที` }
let activity=[]
function renderLog(){const text=activity.map(x=>`[${x.at}] ${x.level==='error'?'ERROR':'INFO'}\n${x.message}`).join('\n\n');$('#log-text').textContent=text||'ยังไม่มีรายการ';$('#activity-summary').textContent=activity.length?activity.at(-1).message.split('\n')[0]:'บันทึกพร้อมใช้งาน';$('#activity-button').classList.toggle('has-error',activity.some(x=>x.level==='error'))}
async function load(){ const d=await manager.overview(); $('#count').textContent=d.clones.length; $('#version').textContent=`Manager ${d.version}`; $('#main-version').textContent=`Freebuff ${d.mainVersion||'ไม่ทราบ'}`; $('#cards').innerHTML=d.clones.map(c=>`<article class="card"><div class="card-head"><div class="avatar">${c.IconLetter||c.Name.slice(-1)}</div><span class="muted">${c.installed?'พร้อมใช้':'ยังไม่สร้าง'}${c.Discovered?' · พบจากโฟลเดอร์':''}</span></div><h4>${c.Name}</h4><div class="muted">${reset(c.usage)}</div><div class="meter"><span style="width:${c.usage&&c.usage.limit?Math.max(0,Math.min(100,c.usage.remaining/c.usage.limit*100)):0}%"></span></div><div class="quota"><span>คงเหลือ</span><b>${remaining(c.usage)}</b></div><button class="secondary" data-open="${c.Name}">เปิดบัญชี</button></article>`).join('')||'<p class="muted">ยังไม่มีแอปโคลน</p>'; $('#account-list').innerHTML=d.clones.map(c=>`<div class="account-row"><div><b>${c.Name}</b><div class="muted">${c.installed?'พบไฟล์แอป':'ยังไม่พบไฟล์แอป'}${c.Discovered?' · พบอัตโนมัติ':''} · ${remaining(c.usage)} · ${reset(c.usage)}</div></div><div class="row-actions"><button class="secondary" data-open="${c.Name}">เปิด</button><button class="ghost" data-rename="${c.Name}">เปลี่ยนชื่อ</button><button class="ghost" data-unregister="${c.Name}">เอาออกจากรายการ</button><button class="danger" data-delete="${c.Name}">ลบแอปและโปรไฟล์</button></div></div>`).join('')||'<p class="muted">ยังไม่มีแอปโคลน</p>'; document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run('open-clone',{name:b.dataset.open})); document.querySelectorAll('[data-unregister]').forEach(b=>b.onclick=async()=>{if(confirm(`เอา ${b.dataset.unregister} ออกจากรายการ? ไฟล์และข้อมูลบัญชีจะยังอยู่`)) await run('delete-clone-registration',{name:b.dataset.unregister})}); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(confirm(`ลบไฟล์แอปและโปรไฟล์ของ ${b.dataset.delete} ถาวร? ข้อมูลล็อกอิน/บัญชีจะหาย`)) await run('delete-clone-files',{name:b.dataset.delete})}); document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=async()=>{const name=prompt('ชื่อใหม่ (ขึ้นต้นด้วย Freebuff)',b.dataset.rename);if(name&&name!==b.dataset.rename)await run('rename-clone',{oldName:b.dataset.rename,name})}) }
async function run(a,p){try{const r=await manager.run(a,p);if(r.message&&!r.silent){activity.push({at:new Date().toLocaleString(),level:'info',message:r.message});renderLog()}await load()}catch(e){await manager.recordError(e.message)}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active');$('#title').textContent=b.querySelector('span').textContent})
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>run(b.dataset.action))
let updateState=null
async function checkUpdates(){try{toast('กำลังตรวจ GitHub Releases…');updateState=await manager.checkUpdates();$('#language-version').textContent=`ปัจจุบัน ${updateState.language.current} · ล่าสุด ${updateState.language.latest}`;$('#manager-version').textContent=`ปัจจุบัน ${updateState.manager.current} · ล่าสุด ${updateState.manager.latest}`;const lb=$('#update-language'),mb=$('#update-manager');lb.disabled=!updateState.language.available;mb.disabled=!updateState.manager.available;lb.textContent=updateState.language.available?'อัปเดตภาษาไทย':'เป็นเวอร์ชันล่าสุด';mb.textContent=updateState.manager.available?'อัปเดต Manager':'เป็นเวอร์ชันล่าสุด';$('#update-all').disabled=!(updateState.language.available||updateState.manager.available);$('#release').textContent=updateState.notes||'ตรวจสอบ Release ล่าสุดเรียบร้อยแล้ว';toast('ตรวจสอบอัปเดตแล้ว')}catch(e){await manager.recordError(e.message)}}
async function installUpdate(kind){try{toast('กำลังดาวน์โหลดและตรวจ SHA-256…');const r=await manager.installUpdate(kind);activity.push({at:new Date().toLocaleString(),level:'info',message:r.message});renderLog();if(!r.restart)await checkUpdates()}catch(e){await manager.recordError(e.message)}}
$('#refresh').onclick=load;$('#close-log').onclick=()=>$('#log').close();$('#activity-button').onclick=async()=>{activity=await manager.activityLog();renderLog();$('#log').showModal()};$('#copy-log').onclick=async()=>{await navigator.clipboard.writeText($('#log-text').textContent);$('#activity-summary').textContent='คัดลอก Log แล้ว'};$('#clear-log').onclick=()=>{activity=[];renderLog()};manager.onActivityLog(entry=>{activity.push(entry);if(activity.length>300)activity.shift();renderLog()});$('#check-update').onclick=checkUpdates;$('#update-language').onclick=()=>installUpdate('language');$('#update-manager').onclick=()=>installUpdate('manager');$('#update-all').onclick=async()=>{if(updateState?.language.available)await installUpdate('language');if(updateState?.manager.available)await installUpdate('manager')}
$('#rebuild-clones').onclick=()=>run('rebuild-clones');$('#add-clone').onclick=()=>{const input=$('#new-clone-name');const name=input.value.trim();if(name)run('add-clone',{name})};load();setInterval(load,60000)
